spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: accounts-service
          uri: http://localhost:8082
          predicates:
            - Path=/accounts/**
        - id: fraud-mgnt-service
          uri: http://localhost:8083
          predicates:
             - Path=/books/**
        - id: investigation-service
          uri: http://localhost:8084
          predicates:
             - Path=/investigation/**
        - id: notifications-service
          uri: http://localhost:8085
          predicates:
             - Path=/notifications/**
        - id: txn-service
          uri: http://localhost:8086
          predicates:
             - Path=/transactions/**